name = "Schistoxpkg"
uuid = "ee8521ae-8f6d-4bf5-8f15-d671735ac7b0"
authors = ["Matthew"]
version = "1.1.01"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
[compat]
Distributions = "0"
JLD = "0"
julia = "1"
Plots = "1"
TimerOutputs= "0"
Documenter = "0"
PyPlot = "2"
[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
